### ISSUE TITLE
Include shallow node modules

### ISSUE THREAD

**Issue by bagrounds** [pahen/madge#112]
First of all, I love this module, and have been using it in various projects for a while now. Thanks!

Unfortunately, it seems like a lot of projects that I might depend on have enormous dependency trees.
To keep the graph reasonable, I currently exclude npm modules.
This is nice, as it gives me a graph of dependencies internal to my project, but it excludes all information about dependencies that I've imported.

I would like to be able to generate a graph that includes all of my external dependencies (node modules) as leaf nodes.

So, for example, if I require madge in my project, I'd like to see a leaf node for madge, but none of madge's dependencies.

I wouldn't be surprised if this can be accomplished with the current implementation - I just haven't figured out how to do it yet.

Any ideas?

Thanks!

**Comment by bagrounds** [comment]
@pahen any ideas? (not sure if github alerts you when issues are created)

**Comment by pahen** [comment]
Glad you like it! I did get the alert :) Busy at the moment though. But I'll will look into it soon. Must think about the best approach to solve it. It's not possible with current solution.

**Comment by bagrounds** [comment]
Great - thanks for the reply!

I played around with the -x option a little bit, trying to see if I could find a regular expression to match deep dependencies, but haven't had much luck with that yet.

I'll let you know if I think of anything.

**Comment by pahen** [comment]
I just wanted to let you know that I think I've found a solution that should work @bagrounds :)
I'll let you know when you can test it.

**Comment by pahen** [comment]
This has been fixed in v1.6.0 now @bagrounds. I've changed the behaviour of the option `includeNpm` and the new `--include-npm` to always be shallow since I don't see any case where you actually wan't traverse into node_modules. Give it as spin and see if it works as expected now :)

<img width="480" alt="screen shot 2017-02-08 at 12 58 58" src="https://cloud.githubusercontent.com/assets/353888/22736439/68c81530-edfe-11e6-8f7a-ec28d51d0bcf.png">

It will also show a CLI spinner and the currently processed thanks to the feature added in https://github.com/dependents/node-dependency-tree/pull/63 @mrjoelkemp 

<img width="907" alt="screen shot 2017-02-08 at 12 55 09" src="https://cloud.githubusercontent.com/assets/353888/22736337/e416ed02-edfd-11e6-83b8-a358ecdcf153.png">

**Comment by mrjoelkemp** [comment]
Woot! Awesome work

**Comment by bagrounds** [comment]
@pahen Thank you! It works!!

I tested this out on a [library](https://www.npmjs.com/package/fun-predicate) of mine, and here are the results:

Before:
![before](https://cloud.githubusercontent.com/assets/4107454/22756718/e2c6b744-edfc-11e6-8fbc-412d07f9c5b3.png)

After:
![after](https://cloud.githubusercontent.com/assets/4107454/22756747/ff8a071e-edfc-11e6-907c-dd3b7796541a.png)

This is exactly the behavior I was hoping for - now I can clearly see how each internal module depends on external modules.

**Comment by pahen** [comment]
Sweet! :)
