### ISSUE TITLE
Feature request: List roots

### ISSUE THREAD

**Issue by AlbinTheander** [pahen/madge#116]
One thing I use my dependency tree for is to find the roots, the packages that no-one is depending upon. Mostly to find stray files that are no longer used in larger projects.

It would be neat if Madge could list the roots directly from the command line.

**Comment by pahen** [comment]
You can always achieve that with some help from grep like this `madge --summary src/app | grep '^0'`. But I agree that it would be nice to maybe have an option for it.

**Comment by pahen** [comment]
Sorry, that didn't solve your problem at all. I suppose we need to add such feature. I'll look into adding a new option called `--orphans` to list all modules that no-one is depending on.

**Comment by AlbinTheander** [comment]
Sounds great. Thanks for the response!

**Comment by mrjoelkemp** [comment]
@pahen Do you think that this makes sense to be a part of dependency-tree proper? Even the sniff for circular dependencies or any other non-visualization operations on the dependency tree seem outside of the scope of madge.

A while back, I was thinking about a 6.0 version of dependency tree that exported a class instead of a pure function. This way, it could have all of the methods (find orphans, find dependents, etc) that leverage the generated tree. Madge would use it via the [toJSON](https://github.com/dependents/node-dependency-tree/pull/42/files#diff-168726dbe96b3ce427e7fedce31bb0bcR272) method or generate the graphviz nodes during the tree generation process (possibly a perf gain for large trees to avoid a second pass). 

I don't have strong opinions on this, so I'm fine either way; just seeing an opportunity (similar to the extraction of the tree generation logic) to avoid muddying the semantics of madge. Thoughts?

**Comment by pahen** [comment]
@mrjoelkemp I would love to move out such features in the long term from madge to dependency-tree. But since this is such a small feature I'll add it to madge for now. But let's pick up this ball on a later point :)

**Comment by mrjoelkemp** [comment]
Sounds good!

**Comment by pahen** [comment]
Added `--orphans` in v.2.0.0 now @AlbinTheander :)

**Comment by AlbinTheander** [comment]
Sounds great. I'll give it a try as soon as possible.

Thanks for all the great work!! :-)
