### ISSUE TITLE
Add caching

### ISSUE THREAD

**Issue by Alexis-benoist** [pahen/madge#123]
Thanks for creating madge !
When we run madge on our project in 40s, do you think that implementing could be useful?

**Comment by pahen** [comment]
Add caching could be useful. But I'm interested in how you use madge to see if there's any other way we can improve the speed.

**Comment by Alexis-benoist** [comment]
We just do `madge --circular .` on our es6 code base.

2017-07-18 12:18 GMT+02:00 Patrik Henningsson <notifications@github.com>:

**Comment by rafaelparpinelcavina** [comment]
hello @pahen, i'm working on the same project as @Alexis-benoist .
to give you some more technical details, if you think it could be helpful:
- we have 491 files in our js project (about 50k lines of code total, i guess)
- we use it as a precommit hook for preventing people to insert circular imports in our master codebase
- it takes 50s running it in local (and then in our CI machines, that are a bit slower it takes 1m30s)

the usage issue is that it is not the only precommit hook we use, so it adds 50s on top of other hooks, if it takes too long our dev team may start to bypass the hook our decide not to put it, but we do think it adds value to the code quality

we don't know exactly how the algorithm for finding circular imports works, but using the fact that the graph of imports may have distinct connected components and running the search for such imports in these components in parallel could be an improvement axis... or maybe caching the imports graph and updating it based on the files that changed since the last time we ran `madge --circular .` could also be useful, as suggested by @Alexis-benoist .

happy to discuss about it.

**Comment by pahen** [comment]
Since you let madge scan the entire project for files you may have folders that contain big files, like a build or dist folder that will cause very bad performance. So ensure this isn't the case by running madge on the specific entry point file of your app instead and see if it makes any difference. If this is still the case, is your project publicly available so I can do some profiling?

**Comment by pahen** [comment]
Did you test my suggestion @Alexis-benoist @rafaelparpinelcavina ?

**Comment by oztune** [comment]
I see that this is a very old issue, but it still seems relevant to me. For me it takes ~15 secs. That's honestly surprisingly fast for our repo size, but still, waiting 15 seconds is a lot when I want to quickly iterate and run successive tests.

Do you think it'd make sense to implement something like this:
```
# First, generate a cache file
madge . > myCacheFile
```

```
# Then feed it in whenever you want
madge --cache ./myCacheFile --orphans
```

**Comment by pahen** [comment]
> I see that this is a very old issue, but it still seems relevant to me. For me it takes ~30 secs to run `madge`. That's honestly surprisingly fast for our repo size, but still, waiting 30 seconds is a lot when I want to quickly iterate and run successive tests.
> 
> Do you think it'd make sense to implement something like this:
> 
> ```
> # First, generate a cache file
> madge . > myCacheFile
> ```
> 
> ```
> # Then feed it in whenever you want
> madge --cache ./myCacheFile --orphans
> ```

You can already do this by using --json and --stdin

```
madge src --json > /tmp/deps.json
```

```
cat /tmp/deps.json | madge --stdin --orphans
```

**Comment by oztune** [comment]
That's great to know, thanks!
