### ISSUE TITLE
Support NODE_PATH variable

### ISSUE THREAD

**Issue by MaxSchlueter** [pahen/madge#143]
Is there a way to specify the search paths for madge? Like the NODE_PATH environment variable for node?

**Comment by pahen** [comment]
Can you please give some more info? What's your use-case for this?

**Comment by aabril** [comment]
@MaxSchlueter I came across to the same question, and probably --base-dir parameter is what you're looking for.

**Comment by tkruczek** [comment]
I have similar issue, I set NODE_PATH to project dir to use project relative paths in all require statements instead of file relative paths, so
require("app/something/a.js");
instead of:
require("../../a.js");

Looks like madge doesn't process such require statements. I tried --basedir but it didn't help.

**Comment by pahen** [comment]
This must be fixed in https://github.com/dependents/node-filing-cabinet. Please create an issue there :)
