### ISSUE TITLE
1:1 circual dependencie not found in ts, but in generated js

### ISSUE THREAD

**Issue by palinka** [pahen/madge#184]
Just encountered on this fork https://github.com/palinka/jolocom-lib/commit/22b56e29146ec457af51be1b1db6b0eea87d2b09

To reproduce comfortably _js_ must be compiled, e.g.

```
git clone https://github.com/palinka/jolocom-lib
git checkout -b potentialTSBug origin/challange/#5-circular
yarn install
tsc
```
I use node --version v8.12.0.

Then

```
madge --circular ts/*
✔ No circular dependency found!
```

(although there)

```
madge --circular js/*
✖ Found 1 circular dependency!

1) identityWallet/identityWallet.js > registries/jolocomRegistry.js
```

**Comment by mrjoelkemp** [comment]
Thanks for reporting @palinka! I think the issue is with this https://github.com/dependents/node-filing-cabinet/blob/master/index.js#L175. Related to #167 and #179, we should be supporting the tsconfig and using the `module` attribute in there to help inform the ts compiler how to resolve the imports.

My hunch on why the compiled output works is that the compiled output is commonjs, which madge's underlying lib (dependency-tree) detects and handles just fine. 

I'll try to carve out some time to fix this since it's come up a few times already.

**Comment by palinka** [comment]
@mrjoelkemp Thanks for your very fast reaction! I updated the issue pointing out e.g. which branch to use such that I hope that an eventual test on your side will not take any boiler-plate.

**Comment by mrjoelkemp** [comment]
Hey @palinka. I just pushed tsconfig support through dependency tree and filing cabinet. I don't have a test ensuring that it'll detect the circ dependency, but I'm basically passing the entire `compilerOptions` portion of the tsconfig to typescript itself to resolve dependencies to files on the filesystem.

The last piece of the puzzle is adding tsConfig support to madge and bumping the dependency-tree version to 6.3.0 if anyone wants to give it a shot.
