### ISSUE TITLE
Hangs on windows when generating an image

### ISSUE THREAD

**Issue by damiangreen** [pahen/madge#324]
On our app of 2000+ components .

It apparently just hangs when attempting to generate the image
(Windows)

```  madge --extensions ts,tsx src/ -i img.png
Processed 4200 files (15.1s) (268 warnings)
```

**Comment by SebTVisage** [comment]
Same issue on mac using the CLI. I run it on the `dist` folder of a node project using JS & TS to avoid any issue related to TS.

Tried with v5 instead v6 (`npm i -g madge@^5`), it worked.

**Comment by PabloLION** [comment]
Seems this is a performance issue. Since we are not planning to work on it recently, this work around can be very helpful. Thanks!

**Comment by epreston** [comment]
Graphs silently fail since upgrading to 6.  Downgrading to 5 sorted things out.

**Comment by kamiazya** [comment]
There was an issue with the ts-graphviz package.

It has been fixed in [v1.5.3](https://github.com/ts-graphviz/ts-graphviz/releases/tag/v1.5.3), so reinstalling madge@6 should not reproduce this issue.

Please let me know if you reproduce this issue again, as I will close this issue once it is closed.

**Comment by epreston** [comment]
Working well.  Thank you.
